services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: linkedinclone-sql
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "StrongPassword123!"
    volumes:
      - linkedinclone_sql_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  linkedinclone_sql_data:
